version: 0.2

phases:
  pre_build:
    commands:
      - docker build -t helloworld .
  build:
    commands:
      - docker images
      - echo "I am Sunny bhai to bhai hai"
      - docker run helloworld echo "Hello, World!" 
